# url: "https://zoldof.com"
# baseurl: /algo-notes-ci
google_site_verification: "iftMWxWANpsgvxI_uGQFejVc_20AYBDnGFsmsrB19VE"
cdn_base: "https://cdn.jsdelivr.net/gh/zoldof/algo-notes-ci@commit-hash/docs"
title: "アルゴリズム×数学の学び直し"
markdown: kramdown
kramdown:
  input: GFM       # GitHub Flavored Markdown
  hard_wrap: true  # 改行を <br> に変換
exclude:
  - assets/style.css      # 圧縮済みのファイルを除外
  - dist-marked
  - index.html
plugins:
  - jekyll-sitemap
