# url: "https://zoldof.com"
# baseurl: /algo-notes-ci
cdn_base: "https://cdn.jsdelivr.net/gh/zoldof/algo-notes-ci@main/docs"
markdown: kramdown
kramdown:
  input: GFM       # GitHub Flavored Markdown
  hard_wrap: true  # 改行を <br> に変換
exclude:
  - assets/style.css      # 圧縮済みのファイルを除外
  - dist-marked
plugins:
  - jekyll-sitemap
